/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package equipo3.proyecto_intermodular;

/**
 *
 * @author david
 */
public class InterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterfazGrafica
     */
    private MetodosBD mysql = new MetodosBD();
    
            
    public InterfazGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        TituloBanco = new javax.swing.JLabel();
        LogoBanco = new javax.swing.JLabel();
        ListarClientes = new javax.swing.JButton();
        InsertarClientes = new javax.swing.JButton();
        PanelCreacionClientes = new javax.swing.JPanel();
        PanelDatosCliente = new javax.swing.JPanel();
        jLabelNif1 = new javax.swing.JLabel();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelTelefono1 = new javax.swing.JLabel();
        txtDNI1 = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        txtTelefono1 = new javax.swing.JTextField();
        btnComprobar1 = new javax.swing.JButton();
        PanelDatosPerfil = new javax.swing.JPanel();
        jLabelDireccion9 = new javax.swing.JLabel();
        jLabelLocalidad9 = new javax.swing.JLabel();
        jLabelAnio9 = new javax.swing.JLabel();
        jLabelSuperficie9 = new javax.swing.JLabel();
        jLabelPrecio9 = new javax.swing.JLabel();
        txtDireccion9 = new javax.swing.JTextField();
        txtAnio9 = new javax.swing.JTextField();
        txtSuperficie9 = new javax.swing.JTextField();
        txtPrecio9 = new javax.swing.JTextField();
        cmbLocalidad9 = new javax.swing.JComboBox<>();
        btnInsertar1 = new javax.swing.JButton();
        btnVolver1 = new javax.swing.JButton();
        PanelSeleccionClientes = new javax.swing.JPanel();
        DatosClientes = new javax.swing.JPanel();
        muestroDatos = new javax.swing.JLabel();
        btnVolver2 = new javax.swing.JButton();
        ListarTodosClientes = new javax.swing.JButton();
        InsertaDni = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloBanco.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TituloBanco.setForeground(new java.awt.Color(0, 153, 102));
        TituloBanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloBanco.setText("TTT BANK");

        LogoBanco.setIcon(new javax.swing.ImageIcon("D:\\logo-color.png")); // NOI18N

        ListarClientes.setText("Listar Clientes");
        ListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarClientesActionPerformed(evt);
            }
        });

        InsertarClientes.setText("Insertar Clientes");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LogoBanco)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(InsertarClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ListarClientes)))
                .addContainerGap(115, Short.MAX_VALUE))
            .addComponent(TituloBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TituloBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarClientes)
                    .addComponent(InsertarClientes))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        // TODO add your handling code here:
        PanelPrincipal.setVisible(false);
        PanelSeleccionClientes.setVisible(false);
        PanelCreacionClientes.setVisible(true);

        PanelDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del propietario"));

        jLabelNif1.setText("NIF:");

        jLabelNombre1.setText("Nombre:");

        jLabelTelefono1.setText("Telefono:");

        txtDNI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNI1ActionPerformed(evt);
            }
        });

        btnComprobar1.setText("Comprobar Propietario");
        btnComprobar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDatosClienteLayout = new javax.swing.GroupLayout(PanelDatosCliente);
        PanelDatosCliente.setLayout(PanelDatosClienteLayout);
        PanelDatosClienteLayout.setHorizontalGroup(
            PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNif1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTelefono1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                        .addComponent(txtDNI1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnComprobar1))
                    .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombre1)
                        .addComponent(txtTelefono1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        PanelDatosClienteLayout.setVerticalGroup(
            PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNif1)
                    .addComponent(txtDNI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprobar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre1)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono1)
                    .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        PanelDatosPerfil.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Inmueble"));

        jLabelDireccion9.setText("Direccion:");

        jLabelLocalidad9.setText("Localidad:");

        jLabelAnio9.setText("Año de construccion:");

        jLabelSuperficie9.setText("Superficie: ");

        jLabelPrecio9.setText("Precio:");

        javax.swing.GroupLayout PanelDatosPerfilLayout = new javax.swing.GroupLayout(PanelDatosPerfil);
        PanelDatosPerfil.setLayout(PanelDatosPerfilLayout);
        PanelDatosPerfilLayout.setHorizontalGroup(
            PanelDatosPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPrecio9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDireccion9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLocalidad9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSuperficie9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAnio9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDireccion9)
                    .addComponent(txtAnio9)
                    .addComponent(txtSuperficie9)
                    .addComponent(txtPrecio9)
                    .addComponent(cmbLocalidad9, 0, 228, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        PanelDatosPerfilLayout.setVerticalGroup(
            PanelDatosPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosPerfilLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PanelDatosPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDireccion9)
                    .addComponent(txtDireccion9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocalidad9)
                    .addComponent(cmbLocalidad9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAnio9)
                    .addComponent(txtAnio9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSuperficie9)
                    .addComponent(txtSuperficie9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecio9)
                    .addComponent(txtPrecio9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        btnInsertar1.setText("Insertar Inmueble");
        btnInsertar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertar1ActionPerformed(evt);
            }
        });

        btnVolver1.setText("Volver");
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });

        PanelCreacionClientes.setVisible(false);

        javax.swing.GroupLayout PanelCreacionClientesLayout = new javax.swing.GroupLayout(PanelCreacionClientes);
        PanelCreacionClientes.setLayout(PanelCreacionClientesLayout);
        PanelCreacionClientesLayout.setHorizontalGroup(
            PanelCreacionClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCreacionClientesLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(PanelCreacionClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCreacionClientesLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(PanelCreacionClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelDatosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelDatosPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCreacionClientesLayout.createSequentialGroup()
                        .addComponent(btnInsertar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                        .addComponent(btnVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        PanelCreacionClientesLayout.setVerticalGroup(
            PanelCreacionClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCreacionClientesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(PanelDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDatosPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelCreacionClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar1)
                    .addComponent(btnVolver1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        PanelSeleccionClientes.setEnabled(false);

        muestroDatos.setText("jLabel1");

        javax.swing.GroupLayout DatosClientesLayout = new javax.swing.GroupLayout(DatosClientes);
        DatosClientes.setLayout(DatosClientesLayout);
        DatosClientesLayout.setHorizontalGroup(
            DatosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosClientesLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(muestroDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        DatosClientesLayout.setVerticalGroup(
            DatosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(muestroDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        btnVolver2.setText("Volver");
        btnVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver2ActionPerformed(evt);
            }
        });

        ListarTodosClientes.setText("Listar todos los clientes");
        ListarTodosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarTodosClientesActionPerformed(evt);
            }
        });

        InsertaDni.setText("Inserta el Dni");
        InsertaDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertaDniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSeleccionClientesLayout = new javax.swing.GroupLayout(PanelSeleccionClientes);
        PanelSeleccionClientes.setLayout(PanelSeleccionClientesLayout);
        PanelSeleccionClientesLayout.setHorizontalGroup(
            PanelSeleccionClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeleccionClientesLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(DatosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSeleccionClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSeleccionClientesLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(InsertaDni)
                .addGap(18, 18, 18)
                .addComponent(ListarTodosClientes)
                .addGap(114, 114, 114))
        );
        PanelSeleccionClientesLayout.setVerticalGroup(
            PanelSeleccionClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSeleccionClientesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(DatosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelSeleccionClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarTodosClientes)
                    .addComponent(InsertaDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnVolver2)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelCreacionClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(PanelSeleccionClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelCreacionClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(PanelSeleccionClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void ListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarClientesActionPerformed
        // TODO add your handling code here:
        PanelPrincipal.setVisible(false);
        PanelSeleccionClientes.setVisible(true);
        PanelCreacionClientes.setVisible(false);
    }//GEN-LAST:event_ListarClientesActionPerformed

    private void txtDNI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNI1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNI1ActionPerformed

    private void btnComprobar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprobar1ActionPerformed

    private void btnInsertar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertar1ActionPerformed

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        // TODO add your handling code here:
         PanelPrincipal.setVisible(true);
        PanelSeleccionClientes.setVisible(false);
        PanelCreacionClientes.setVisible(false);
    }//GEN-LAST:event_btnVolver1ActionPerformed

    private void btnVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver2ActionPerformed
        // TODO add your handling code here:
         PanelPrincipal.setVisible(true);
        PanelSeleccionClientes.setVisible(false);
        PanelCreacionClientes.setVisible(false);
    }//GEN-LAST:event_btnVolver2ActionPerformed

    private void ListarTodosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarTodosClientesActionPerformed
        // TODO add your handling code here:
        
        String a  = mysql.seleccionClientePorDni(InsertaDni.getText()).toString();
        muestroDatos.setText(a);
    }//GEN-LAST:event_ListarTodosClientesActionPerformed

    private void InsertaDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertaDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertaDniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DatosClientes;
    private javax.swing.JTextField InsertaDni;
    private javax.swing.JButton InsertarClientes;
    private javax.swing.JButton ListarClientes;
    private javax.swing.JButton ListarTodosClientes;
    private javax.swing.JLabel LogoBanco;
    private javax.swing.JPanel PanelCreacionClientes;
    private javax.swing.JPanel PanelDatosCliente;
    private javax.swing.JPanel PanelDatosPerfil;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelSeleccionClientes;
    private javax.swing.JLabel TituloBanco;
    private javax.swing.JButton btnComprobar1;
    private javax.swing.JButton btnInsertar1;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JButton btnVolver2;
    private javax.swing.JComboBox<String> cmbLocalidad;
    private javax.swing.JComboBox<String> cmbLocalidad1;
    private javax.swing.JComboBox<String> cmbLocalidad2;
    private javax.swing.JComboBox<String> cmbLocalidad3;
    private javax.swing.JComboBox<String> cmbLocalidad4;
    private javax.swing.JComboBox<String> cmbLocalidad5;
    private javax.swing.JComboBox<String> cmbLocalidad6;
    private javax.swing.JComboBox<String> cmbLocalidad7;
    private javax.swing.JComboBox<String> cmbLocalidad9;
    private javax.swing.JLabel jLabelAnio;
    private javax.swing.JLabel jLabelAnio1;
    private javax.swing.JLabel jLabelAnio2;
    private javax.swing.JLabel jLabelAnio3;
    private javax.swing.JLabel jLabelAnio4;
    private javax.swing.JLabel jLabelAnio5;
    private javax.swing.JLabel jLabelAnio6;
    private javax.swing.JLabel jLabelAnio7;
    private javax.swing.JLabel jLabelAnio9;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelDireccion1;
    private javax.swing.JLabel jLabelDireccion2;
    private javax.swing.JLabel jLabelDireccion3;
    private javax.swing.JLabel jLabelDireccion4;
    private javax.swing.JLabel jLabelDireccion5;
    private javax.swing.JLabel jLabelDireccion6;
    private javax.swing.JLabel jLabelDireccion7;
    private javax.swing.JLabel jLabelDireccion9;
    private javax.swing.JLabel jLabelLocalidad;
    private javax.swing.JLabel jLabelLocalidad1;
    private javax.swing.JLabel jLabelLocalidad2;
    private javax.swing.JLabel jLabelLocalidad3;
    private javax.swing.JLabel jLabelLocalidad4;
    private javax.swing.JLabel jLabelLocalidad5;
    private javax.swing.JLabel jLabelLocalidad6;
    private javax.swing.JLabel jLabelLocalidad7;
    private javax.swing.JLabel jLabelLocalidad9;
    private javax.swing.JLabel jLabelNif1;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelPrecio1;
    private javax.swing.JLabel jLabelPrecio2;
    private javax.swing.JLabel jLabelPrecio3;
    private javax.swing.JLabel jLabelPrecio4;
    private javax.swing.JLabel jLabelPrecio5;
    private javax.swing.JLabel jLabelPrecio6;
    private javax.swing.JLabel jLabelPrecio7;
    private javax.swing.JLabel jLabelPrecio9;
    private javax.swing.JLabel jLabelSuperficie;
    private javax.swing.JLabel jLabelSuperficie1;
    private javax.swing.JLabel jLabelSuperficie2;
    private javax.swing.JLabel jLabelSuperficie3;
    private javax.swing.JLabel jLabelSuperficie4;
    private javax.swing.JLabel jLabelSuperficie5;
    private javax.swing.JLabel jLabelSuperficie6;
    private javax.swing.JLabel jLabelSuperficie7;
    private javax.swing.JLabel jLabelSuperficie9;
    private javax.swing.JLabel jLabelTelefono1;
    private javax.swing.JPanel jPanelDatosInmueble;
    private javax.swing.JPanel jPanelDatosInmueble1;
    private javax.swing.JPanel jPanelDatosInmueble2;
    private javax.swing.JPanel jPanelDatosInmueble3;
    private javax.swing.JPanel jPanelDatosInmueble4;
    private javax.swing.JPanel jPanelDatosInmueble5;
    private javax.swing.JPanel jPanelDatosInmueble6;
    private javax.swing.JPanel jPanelDatosInmueble7;
    private javax.swing.JLabel muestroDatos;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAnio1;
    private javax.swing.JTextField txtAnio2;
    private javax.swing.JTextField txtAnio3;
    private javax.swing.JTextField txtAnio4;
    private javax.swing.JTextField txtAnio5;
    private javax.swing.JTextField txtAnio6;
    private javax.swing.JTextField txtAnio7;
    private javax.swing.JTextField txtAnio9;
    private javax.swing.JTextField txtDNI1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccion1;
    private javax.swing.JTextField txtDireccion2;
    private javax.swing.JTextField txtDireccion3;
    private javax.swing.JTextField txtDireccion4;
    private javax.swing.JTextField txtDireccion5;
    private javax.swing.JTextField txtDireccion6;
    private javax.swing.JTextField txtDireccion7;
    private javax.swing.JTextField txtDireccion9;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecio1;
    private javax.swing.JTextField txtPrecio2;
    private javax.swing.JTextField txtPrecio3;
    private javax.swing.JTextField txtPrecio4;
    private javax.swing.JTextField txtPrecio5;
    private javax.swing.JTextField txtPrecio6;
    private javax.swing.JTextField txtPrecio7;
    private javax.swing.JTextField txtPrecio9;
    private javax.swing.JTextField txtSuperficie;
    private javax.swing.JTextField txtSuperficie1;
    private javax.swing.JTextField txtSuperficie2;
    private javax.swing.JTextField txtSuperficie3;
    private javax.swing.JTextField txtSuperficie4;
    private javax.swing.JTextField txtSuperficie5;
    private javax.swing.JTextField txtSuperficie6;
    private javax.swing.JTextField txtSuperficie7;
    private javax.swing.JTextField txtSuperficie9;
    private javax.swing.JTextField txtTelefono1;
    // End of variables declaration//GEN-END:variables
}
